spring:
  application:
    name: pharma-order-service  
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/smartpharmadb?searchpath=oms_schema
    username: postgres
    password: admin
  jpa:
    open-in-view: false
    hibernate:
      enable_lazy_load_no_trans: true
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect        
    show-sql: true 
server:
  port: 8082
  servlet:
    context-path: /pharma
app:
  config:
    aws:
      region: ap-south-1
      access-key-id: AKIA2NRGLAGWT32XXJO3
      secret-key-id: 93XEvy3K+Hce9gNXyDxBIUB/CAOrBB/Z3IjkN+6N
    message:
      queue:
        topic: order-queue
springdoc:
  api-docs:
    path: /pharma/swagger-ui.html
